/* Wadfun Color History V6 — single source of truth: Color Engine V26 */
(function(){
'use strict';
function root(){return document.querySelector('#color .toolbar')}
function active(){return !!document.getElementById('color')?.classList.contains('active')}
function engineUndo(){const fn=window.wadfunColorUndo;return typeof fn==='function'&&fn!==engineUndo?fn():false}
function engineRedo(){const fn=window.wadfunColorRedo;return typeof fn==='function'&&fn!==engineRedo?fn():false}
function find(kind){const r=root();if(!r)return null;const ids=kind==='undo'?['colorUndoBtn','undoColorBtn']:['colorRedoBtn','redoColorBtn'];for(const id of ids){const b=document.getElementById(id);if(b&&r.contains(b))return b}return [...r.querySelectorAll('button')].find(b=>{const t=(b.textContent||'').toLowerCase();return kind==='undo'?t.includes('ย้อนกลับ')||t.includes('undo'):t.includes('ทำซ้ำ')||t.includes('redo')})||null}
function ensureButtons(){const r=root();if(!r)return false;let u=find('undo'),d=find('redo');if(!u){u=document.createElement('button');u.id='colorUndoBtn';u.type='button';u.className='tb';u.innerHTML='<i>↩️</i><span>ย้อนกลับ</span>';r.appendChild(u)}if(!d){d=document.createElement('button');d.id='colorRedoBtn';d.type='button';d.className='tb';d.innerHTML='<i>↪️</i><span>ทำซ้ำ</span>';if(u.parentElement===r)u.insertAdjacentElement('afterend',d);else r.appendChild(d)}u.dataset.wadfunHistoryV6='1';d.dataset.wadfunHistoryV6='1';if(!u.dataset.wadfunHistoryClick){u.dataset.wadfunHistoryClick='1';u.addEventListener('click',e=>{if(!active())return;e.preventDefault();e.stopImmediatePropagation();engineUndo()},true)}if(!d.dataset.wadfunHistoryClick){d.dataset.wadfunHistoryClick='1';d.addEventListener('click',e=>{if(!active())return;e.preventDefault();e.stopImmediatePropagation();engineRedo()},true)}return true}
function sync(){const u=find('undo'),d=find('redo');const s=typeof window.wadfunColorHistoryState==='function'?window.wadfunColorHistoryState():{undo:0,redo:0};if(u){u.disabled=!s.undo;u.setAttribute('aria-disabled',String(!s.undo));u.title=s.undo?'ย้อนกลับ':'ยังไม่มีสิ่งที่ย้อนกลับ'}if(d){d.disabled=!s.redo;d.setAttribute('aria-disabled',String(!s.redo));d.title=s.redo?'ทำซ้ำ':'ยังไม่มีสิ่งที่ทำซ้ำ'}}
function install(){if(window.__wadfunColorHistoryV6)return;window.__wadfunColorHistoryV6=true;window.wadfunColorHistoryReset=()=>{};window.wadfunColorHistoryRecord=()=>{};window.undoColor=engineUndo;window.redoColor=engineRedo;ensureButtons();sync();setInterval(()=>{if(root()){ensureButtons();sync()}},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
