/* Wadfun Color Engine V22 — Color pen without legacy overlay or start dot. Draw mode untouched. */
(function(){
'use strict';
const LINE_LUMA=248,MIN_ALPHA=18,PAINT_ALPHA=12,MAX_DPR=1.5;
const $=id=>document.getElementById(id);
const luma=(r,g,b)=>.299*r+.587*g+.114*b;
function rgb(h){h=(h||'#e53935').replace('#','');if(h.length===3)h=h.split('').map(x=>x+x).join('');return[parseInt(h.slice(0,2),16)||0,parseInt(h.slice(2,4),16)||0,parseInt(h.slice(4,6),16)||0]}
function mode(){if($('colorPenBtn')?.classList.contains('on'))return'pen';if($('colorEraseBtn')?.classList.contains('on'))return'eraser';return'bucket'}
function selectedColor(){const saved=window.wadfunSelectedColor;if(/^#[0-9a-f]{6}$/i.test(saved||''))return saved;const e=$('colorDot');if(e){const cs=getComputedStyle(e),bg=cs.backgroundColor;const m=bg.match(/\d+(?:\.\d+)?/g);if(m&&m.length>=3)return'#'+m.slice(0,3).map(v=>(+v|0).toString(16).padStart(2,'0')).join('')}return'#e53935'}
let lineCanvas,lineCtx,paintCanvas,paintCtx,mask,mw=0,mh=0,ready=false,resizing=false,internalResize=false,wantedW=0,wantedH=0,wantedCssW=0,wantedCssH=0,dirty=null,renderQueued=false;
function point(c,x,y,r){r=r||c.getBoundingClientRect();return{x:(x-r.left)*c.width/r.width,y:(y-r.top)*c.height/r.height}}
function isLine(d,i){return d[i+3]>=MIN_ALPHA&&luma(d[i],d[i+1],d[i+2])<LINE_LUMA}
function rebuildMask(){const d=lineCtx.getImageData(0,0,mw,mh).data;mask=new Uint8Array(mw*mh);for(let q=0,i=0;q<mw*mh;q++,i+=4)if(isLine(d,i))mask[q]=1}
function build(c){if(!c.width||!c.height)return false;const w=c.width,h=c.height,n=w*h,src=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h);mw=w;mh=h;mask=new Uint8Array(n);lineCanvas=document.createElement('canvas');lineCanvas.width=w;lineCanvas.height=h;lineCtx=lineCanvas.getContext('2d');const ld=lineCtx.createImageData(w,h);for(let q=0,i=0;q<n;q++,i+=4)if(isLine(src.data,i)){mask[q]=1;ld.data[i]=src.data[i];ld.data[i+1]=src.data[i+1];ld.data[i+2]=src.data[i+2];ld.data[i+3]=src.data[i+3]}lineCtx.putImageData(ld,0,0);paintCanvas=document.createElement('canvas');paintCanvas.width=w;paintCanvas.height=h;paintCtx=paintCanvas.getContext('2d');ready=true;wantedW=w;wantedH=h;render(c);return true}
function scaled(s,w,h){const n=document.createElement('canvas');n.width=w;n.height=h;n.getContext('2d').drawImage(s,0,0,w,h);return n}
function resizeInternal(c,w,h){if(!ready||resizing)return;resizing=true;paintCanvas=scaled(paintCanvas,w,h);paintCtx=paintCanvas.getContext('2d');lineCanvas=scaled(lineCanvas,w,h);lineCtx=lineCanvas.getContext('2d');mw=w;mh=h;rebuildMask();wantedW=w;wantedH=h;render(c);resizing=false}
function sync(){const c=$('colorCanvas'),v=$('colorViewport');if(!c||!v||!ready||resizing)return;const r=v.getBoundingClientRect(),cw=Math.max(50,Math.round(r.width)),ch=Math.max(50,Math.round(r.height)),d=Math.min(devicePixelRatio||1,MAX_DPR),w=Math.round(cw*d),h=Math.round(ch*d);wantedCssW=cw;wantedCssH=ch;c.style.width=cw+'px';c.style.height=ch+'px';if(c.width!==w||c.height!==h){internalResize=true;c.width=w;c.height=h;resizeInternal(c,w,h);internalResize=false}else{wantedW=w;wantedH=h;render(c)}}
function render(c){if(!ready)return;const x=c.getContext('2d');x.setTransform(1,0,0,1,0,0);x.globalAlpha=1;x.globalCompositeOperation='source-over';x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(paintCanvas,0,0);x.drawImage(lineCanvas,0,0)}
function renderDirty(c,r){const x=c.getContext('2d');x.save();x.setTransform(1,0,0,1,0,0);x.globalCompositeOperation='source-over';x.clearRect(r.x,r.y,r.w,r.h);x.fillStyle='#fff';x.fillRect(r.x,r.y,r.w,r.h);x.drawImage(paintCanvas,r.x,r.y,r.w,r.h,r.x,r.y,r.w,r.h);x.drawImage(lineCanvas,r.x,r.y,r.w,r.h,r.x,r.y,r.w,r.h);x.restore()}
function requestRender(c,x,y,w,h){const r={x:Math.max(0,Math.floor(x)),y:Math.max(0,Math.floor(y)),w:Math.max(1,Math.ceil(w)),h:Math.max(1,Math.ceil(h))};if(!dirty)dirty=r;else{const X=Math.min(dirty.x,r.x),Y=Math.min(dirty.y,r.y),EX=Math.max(dirty.x+dirty.w,r.x+r.w),EY=Math.max(dirty.y+dirty.h,r.y+r.h);dirty={x:X,y:Y,w:EX-X,h:EY-Y}}if(!renderQueued){renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;const q=dirty;dirty=null;if(q)renderDirty(c,q)})}}
function samePaint(d,i,p,base){const a=d[i+3];if(base)return a<=PAINT_ALPHA;if(a<=PAINT_ALPHA)return false;return Math.abs(d[i]-p[0])<=3&&Math.abs(d[i+1]-p[1])<=3&&Math.abs(d[i+2]-p[2])<=3}
function fillRegion(x,y,hex){if(!paintCtx||!mask)return false;const w=mw,h=mh;x=Math.max(0,Math.min(w-1,x|0));y=Math.max(0,Math.min(h-1,y|0));const start=y*w+x;if(mask[start])return false;const im=paintCtx.getImageData(0,0,w,h),d=im.data,si=start*4,base=d[si+3]<=PAINT_ALPHA,p=[d[si],d[si+1],d[si+2]],t=rgb(hex);let changed=false,stack=[start];while(stack.length){const seed=stack.pop(),sy=(seed/w)|0,sx=seed-sy*w;if(mask[seed])continue;let lx=sx,rx=sx;while(lx>=0&&!mask[sy*w+lx]&&samePaint(d,(sy*w+lx)*4,p,base))lx--;lx++;while(rx<w&&!mask[sy*w+rx]&&samePaint(d,(sy*w+rx)*4,p,base))rx--;rx--;if(lx>rx)continue;for(let xx=lx;xx<=rx;xx++){const i=(sy*w+xx)*4;if(d[i]!==t[0]||d[i+1]!==t[1]||d[i+2]!==t[2]||d[i+3]!==255)changed=true;d[i]=t[0];d[i+1]=t[1];d[i+2]=t[2];d[i+3]=255}for(const ny of [sy-1,sy+1])if(ny>=0&&ny<h){let xx=lx;while(xx<=rx){const q=ny*w+xx;if(mask[q]||!samePaint(d,q*4,p,base)){xx++;continue}stack.push(q);while(xx<=rx&&!mask[ny*w+xx]&&samePaint(d,(ny*w+xx)*4,p,base))xx++}}}if(changed){paintCtx.putImageData(im,0,0);render($('colorCanvas'))}return changed}
let undo=[];
function saveUndo(){if(paintCanvas)undo.push(paintCanvas.toDataURL());if(undo.length>30)undo.shift()}
function undoColorV22(){if(!paintCanvas||!undo.length)return;const im=new Image(),src=undo.pop();im.onload=()=>{paintCtx.clearRect(0,0,mw,mh);paintCtx.drawImage(im,0,0);render($('colorCanvas'))};im.src=src}
function reset(){const c=$('colorCanvas');if(!c)return;ready=false;undo=[];build(c);sync()}
function draw(a,b,m,c){const size=(m==='eraser'?(typeof eraserSize!=='undefined'?eraserSize:30):(typeof colorBrushSize!=='undefined'?colorBrushSize:22))*Math.min(devicePixelRatio||1,MAX_DPR),pad=size/2+4,sx=Math.max(0,Math.floor(Math.min(a.x,b.x)-pad)),sy=Math.max(0,Math.floor(Math.min(a.y,b.y)-pad)),ex=Math.min(c.width,Math.ceil(Math.max(a.x,b.x)+pad)),ey=Math.min(c.height,Math.ceil(Math.max(a.y,b.y)+pad));paintCtx.save();paintCtx.globalCompositeOperation=m==='eraser'?'destination-out':'source-over';paintCtx.strokeStyle=m==='eraser'?'#000':selectedColor();paintCtx.fillStyle=paintCtx.strokeStyle;paintCtx.lineWidth=size;paintCtx.lineCap='round';paintCtx.lineJoin='round';paintCtx.beginPath();paintCtx.moveTo(a.x,a.y);paintCtx.lineTo(b.x,b.y);paintCtx.stroke();paintCtx.restore();requestRender(c,sx,sy,ex-sx,ey-sy)}
function install(){const c=$('colorCanvas'),v=$('colorViewport'),z=$('colorZoom');if(!c||!v||!z||c.dataset.colorV22)return false;c.dataset.colorV22='1';reset();window.wadfunColorTemplateChanged=reset;window.wadfunColorResizeToViewport=sync;window.undoColor=undoColorV22;const tap=(x,y)=>{if(mode()!=='bucket')return;saveUndo();const p=point(c,x,y);if(!fillRegion(p.x,p.y,selectedColor()))undo.pop()};if(window.wadfunBindTapCanvas)window.wadfunBindTapCanvas(c,v,z,'color',tap);
let active=false,pid=null,last=null,rect=null,queue=[],raf=0,touchIds=new Set(),snapshot=null;
function flush(){raf=0;if(!active)return;let p=last,m=mode();for(const q of queue){const n=point(c,q.x,q.y,rect);draw(p,n,m,c);p=n}queue=[];last=p}
function schedule(){if(!raf)raf=requestAnimationFrame(flush)}
function begin(x,y,id){rect=c.getBoundingClientRect();last=point(c,x,y,rect);active=true;pid=id}
function cancelStroke(){if(snapshot){const im=new Image(),s=snapshot;snapshot=null;im.onload=()=>{paintCtx.clearRect(0,0,mw,mh);paintCtx.drawImage(im,0,0);render(c)};im.src=s}active=false;pid=null;queue=[]}
function down(e){if(mode()==='bucket')return;if(e.pointerType==='touch'){touchIds.add(e.pointerId);if(touchIds.size>1){cancelStroke();e.preventDefault();e.stopImmediatePropagation();return}snapshot=paintCanvas.toDataURL();begin(e.clientX,e.clientY,e.pointerId);return}e.preventDefault();e.stopImmediatePropagation();saveUndo();begin(e.clientX,e.clientY,e.pointerId)}
function move(e){if(e.pointerType==='touch'&&touchIds.size>1){e.preventDefault();e.stopImmediatePropagation();return}if(e.pointerId!==pid)return;e.preventDefault();e.stopImmediatePropagation();const es=e.getCoalescedEvents?e.getCoalescedEvents():[e];for(const q of es)queue.push({x:q.clientX,y:q.clientY});schedule()}
function up(e){if(e.pointerType==='touch'){touchIds.delete(e.pointerId);if(e.pointerId===pid){flush();active=false;pid=null;rect=null;queue=[];snapshot=null;e.preventDefault();e.stopImmediatePropagation()}return}if(e.pointerId===pid){end();e.preventDefault();e.stopImmediatePropagation()}}
function end(){if(!active)return;flush();active=false;pid=null;rect=null;queue=[];snapshot=null}
function cleanupLegacy(){if(!ready)return;if(mode()==='bucket')return;if(active)flush();render(c)}
v.addEventListener('pointerdown',down,{capture:true,passive:false});v.addEventListener('pointermove',move,{capture:true,passive:false});v.addEventListener('pointerup',up,{capture:true,passive:false});v.addEventListener('pointercancel',up,{capture:true,passive:false});
/* The original inline Color handler is still present for backward compatibility. These bubble listeners repaint the visible canvas from our isolated paint layer after that legacy handler runs, so it cannot leave red dots/strokes behind. */
c.addEventListener('pointerdown',cleanupLegacy,{capture:false,passive:true});c.addEventListener('pointermove',cleanupLegacy,{capture:false,passive:true});c.addEventListener('pointerup',cleanupLegacy,{capture:false,passive:true});c.addEventListener('pointercancel',cleanupLegacy,{capture:false,passive:true});
if(window.ResizeObserver&&!window.__wadfunColorRO22){window.__wadfunColorRO22=true;const ro=new ResizeObserver(()=>{if($('color')?.classList.contains('active')){clearTimeout(window.__wadfunColorRT22);window.__wadfunColorRT22=setTimeout(sync,50)}});ro.observe(v)}
if(window.MutationObserver&&!window.__wadfunColorGuard22){window.__wadfunColorGuard22=true;new MutationObserver(()=>{if(!ready||internalResize)return;if(c.width!==wantedW||c.height!==wantedH||c.style.width!==wantedCssW+'px'||c.style.height!==wantedCssH+'px')sync()}).observe(c,{attributes:true,attributeFilter:['width','height','style']})}
const wrap=window.loadTemplate;if(typeof wrap==='function'&&!window.__wadfunColorLoad22){window.__wadfunColorLoad22=true;window.loadTemplate=function(){const r=wrap.apply(this,arguments);setTimeout(reset,0);return r}}
return true}
const timer=setInterval(()=>{if(install())clearInterval(timer)},100);
window.wadfunFillRegionV22=fillRegion;window.wadfunResetColorV22=reset;
})();