/* Wadfun Color History V4 — visible Color Redo + reliable Undo/Redo; no duplicate Undo */
(function(){
'use strict';
function active(){return document.getElementById('color')?.classList.contains('active')}
function canvas(){return document.getElementById('colorCanvas')}
let undo=[],redo=[],busy=false,lastState=null;
function snap(){const c=canvas();return c?c.toDataURL('image/png'):null}
function restore(data){if(!data)return false;const c=canvas(),ctx=c?.getContext('2d');if(!c||!ctx)return false;const im=new Image();im.onload=()=>{if(!active())return;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);window.wadfunResetColorMask?.();lastState=data;busy=false;sync()};im.src=data;return true}
function reset(){undo=[];redo=[];lastState=snap();sync()}
function record(before){const now=snap();if(!now||before===now)return;undo.push(before);if(undo.length>30)undo.shift();redo=[];lastState=now;sync()}
function apply(target){const c=canvas(),ctx=c?.getContext('2d');if(!c||!ctx||!target)return false;busy=true;const im=new Image();im.onload=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);window.wadfunResetColorMask?.();lastState=target;busy=false;sync()};im.src=target;return true}
function doUndo(){if(busy||!active()||!undo.length)return false;const current=snap(),target=undo.pop();if(!current||!target)return false;redo.push(current);if(redo.length>30)redo.shift();return apply(target)}
function doRedo(){if(busy||!active()||!redo.length)return false;const current=snap(),target=redo.pop();if(!current||!target)return false;undo.push(current);if(undo.length>30)undo.shift();return apply(target)}
function sync(){window.wadfunColorUndo=doUndo;window.wadfunColorRedo=doRedo;window.wadfunColorHistoryState=()=>({undo:undo.length,redo:redo.length});window.colorUndo=undo;window.colorRedo=redo;updateButtons()}
function findButton(kind){const root=document.querySelector('#color .toolbar');if(!root)return null;const ids=kind==='undo'?['colorUndoBtn','undoColorBtn','undoBtn']:['colorRedoBtn','redoColorBtn','redoBtn'];for(const id of ids){const e=document.getElementById(id);if(e&&root.contains(e))return e}const els=[...root.querySelectorAll('button')];return els.find(e=>{const t=(e.textContent||'').trim().toLowerCase();return kind==='undo'?t.includes('ย้อนกลับ')||t==='undo':t.includes('ทำซ้ำ')||t.includes('redo')})}
function ensureRedoButton(){if(!active())return;const root=document.querySelector('#color .toolbar');if(!root||findButton('redo'))return;const b=document.createElement('button');b.id='colorRedoBtn';b.type='button';b.className='tb';b.setAttribute('aria-label','ทำซ้ำ');b.innerHTML='<i>↪️</i><span>ทำซ้ำ</span>';const u=findButton('undo');if(u&&u.parentElement===root)u.insertAdjacentElement('afterend',b);else root.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();doRedo()},true)}
function updateButtons(){const r=findButton('redo');if(r){r.disabled=redo.length===0;r.setAttribute('aria-disabled',String(redo.length===0));r.title=redo.length?'ทำซ้ำ':'ยังไม่มีสิ่งที่ทำซ้ำ'}const u=findButton('undo');if(u){u.disabled=undo.length===0;u.setAttribute('aria-disabled',String(undo.length===0))}}
function wire(){ensureRedoButton();const u=findButton('undo'),r=findButton('redo');if(u&&!u.dataset.wadfunHistoryV4){u.dataset.wadfunHistoryV4='1';u.addEventListener('click',e=>{if(active()){e.preventDefault();e.stopImmediatePropagation();doUndo()}},true)}if(r&&!r.dataset.wadfunHistoryV4){r.dataset.wadfunHistoryV4='1';r.addEventListener('click',e=>{if(active()){e.preventDefault();e.stopImmediatePropagation();doRedo()}},true)}updateButtons()}
function install(){if(window.__wadfunColorHistoryV4)return true;window.__wadfunColorHistoryV4=true;const oldLoad=window.loadTemplate;if(typeof oldLoad==='function')window.loadTemplate=function(){const r=oldLoad.apply(this,arguments);reset();return r};const oldReset=window.resetColor;if(typeof oldReset==='function')window.resetColor=function(){const r=oldReset.apply(this,arguments);reset();return r};window.addEventListener('wadfun-work-loaded',()=>{if(active())reset()});wire();return true}
window.wadfunColorHistoryRecord=record;window.wadfunColorHistoryReset=reset;setInterval(wire,250);install();
})();
