/* Wadfun Gallery Engine V26 — saved color artworks always create a new record */
(function(){
'use strict';
const S='wadfun-storage.js';let sp=null,editingId=null,hookedFinish=false,hookedGallery=false,autoObserver=null,hookedShow=false,hookedColorExit=false,finishing=false;
function load(){if(window.wadfunStorage)return Promise.resolve(window.wadfunStorage);if(sp)return sp;sp=new Promise((res,rej)=>{const s=document.createElement('script');s.src=S;s.onload=()=>window.wadfunStorage?res(window.wadfunStorage):rej(Error('storage unavailable'));s.onerror=rej;document.head.appendChild(s)});return sp}
const active=()=>document.querySelector('.screen.active')?.id||'';
const canvas=m=>m==='color'?document.getElementById('colorCanvas'):(document.getElementById('drawCanvas')||document.querySelector('.screen.active canvas'));
const image=w=>w?.imageData||w?.img||'';
const esc=s=>String(s??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]));
function colorKey(){const st=window.wadfunColorLibraryState||{},cat=st.category||window.wadfunActiveColorTemplate?.category||'',idx=Number.isInteger(st.index)?st.index:'',name=window.wadfunActiveColorTemplate?.name||window.currentName||'';return cat+':'+idx+':'+name}
function captureColorSnapshot(){try{const c=canvas('color');if(!c||!c.toDataURL||!window.wadfunColorGetState)return null;const imageData=c.toDataURL('image/png'),editorState=window.wadfunColorGetState();if(!imageData||imageData.length<100)return null;return {imageData,editorState,templateKey:colorKey()}}catch(e){console.error('[Wadfun] color snapshot failed',e);return null}}
async function save(mode,snapshot,opts){await load();const m=mode==='color'||active()==='color'?'color':'draw',c=canvas(m),snap=m==='color'&&snapshot?snapshot:null,draft=!!opts?.draft;if(!c||!c.toDataURL)throw Error('canvas not found');const data=snap?.imageData||c.toDataURL('image/png');if(!data||data.length<100)throw Error('empty canvas');
let old=null;const key=m==='color'?(snap?.templateKey||colorKey()):'';
if(m==='color'&&draft){if(key&&key!==':'){const all=await window.wadfunStorage.getAllArtworks();old=all.find(x=>x.mode==='color'&&x.templateKey===key&&x.draft===true)||null}}
else if(m==='draw'&&editingId){old=await window.wadfunStorage.getArtwork(editingId)}
const rec={id:old?.id,name:m==='color'?(window.currentName||'ผลงานระบายสี'):'ผลงานวาดของฉัน',category:m==='color'?(window.wadfunActiveColorTemplate?.category||window.wadfunColorLibraryState?.category||''):'',mode:m,imageData:data,thumbnail:data,templateKey:key,editorState:m==='color'?(snap?.editorState||window.wadfunColorGetState?.()||null):null,createdAt:old?.createdAt||Date.now(),draft:m==='color'?draft:false};
// Drafts may be updated. A completed color save is a brand-new artwork by design.
const out=(!draft&&m==='color')
  ?await window.wadfunStorage.createArtwork(Object.assign({},rec,{id:undefined,draft:false}))
  :await window.wadfunStorage.saveArtwork(rec);
if(!out?.id)throw Error('save failed');if(m==='draw')editingId=out.id;window.wadfunLastFinishSave=out.id;
if(m==='color'&&!draft){const all=await window.wadfunStorage.getAllArtworks();for(const x of all)if(x.mode==='color'&&x.templateKey===key&&x.draft===true)await window.wadfunStorage.deleteArtwork(x.id)}
return out}
async function saveCurrentColor(snapshot){if(!window.wadfunColorGetState)return null;try{return await save('color',snapshot||captureColorSnapshot(),{draft:true})}catch(e){console.error('[Wadfun] color autosave failed',e);return null}}
function shouldSaveBeforeColorExit(target){const b=target?.closest?.('button,.back,[role="button"]');if(!b)return false;if(b.id==='wadfunChangePicture')return true;const text=(b.textContent||'').replace(/\s+/g,' ').trim();return /เปลี่ยนรูป|กลับ.*หมวด|หมวดทั้งหมด|กลับหน้าแรก|กลับ/.test(text)}
function installColorExitCapture(){if(hookedColorExit||!document.body)return;document.addEventListener('click',e=>{if(finishing||active()!=='color'||!shouldSaveBeforeColorExit(e.target))return;const snap=captureColorSnapshot();if(snap)window.wadfunColorAutosaveReady=saveCurrentColor(snap)},true);hookedColorExit=true}
async function finish(mode){const m=mode==='color'||mode==='draw'?mode:(active()==='color'?'color':'draw'),c=canvas(m),snap=m==='color'?captureColorSnapshot():null;const outSaved=await save(m,snap,{draft:false}),out=document.getElementById('finishImg');if(out&&c)out.src=outSaved?.imageData||c.toDataURL('image/png');if(typeof window.show==='function'){finishing=true;try{await window.show('finish')}finally{finishing=false}}return outSaved}
function hookFinish(){if(hookedFinish)return true;if(typeof window.finishCanvas!=='function')return false;window.finishCanvas=finish;window.wadfunFinish=finish;hookedFinish=true;return true}
function cleanHomeMenu(){const menu=document.querySelector('.home .sideMenu');if(!menu)return false;menu.querySelectorAll('.woodBtn').forEach(b=>{const keep=/แกลเลอรี/i.test((b.textContent||'').replace(/\s+/g,''));b.style.display=keep?'':'none'});return true}
function styles(){if(document.getElementById('wadfun-gallery-v21'))return;const s=document.createElement('style');s.id='wadfun-gallery-v21';s.textContent='.wadfun-gallery-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.wadfun-gallery-card{background:#fff;border:2px solid #e2edf2;border-radius:20px;padding:8px;box-shadow:0 8px 22px rgba(43,93,112,.09)}.wadfun-gallery-thumb{display:block;width:100%;aspect-ratio:1;padding:0;border:0;border-radius:14px;background:#f7fbfd;overflow:hidden}.wadfun-gallery-thumb img{width:100%;height:100%;object-fit:contain}.wadfun-gallery-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:7px}.wadfun-gallery-actions button{padding:9px 4px}.wadfun-gallery-share{background:#e8f7ff;border:2px solid #bfe6f7;border-radius:15px;padding:9px 4px;font-weight:1000}.wadfun-gallery-empty{grid-column:1/-1;text-align:center;padding:40px;border:2px dashed #efd47a;border-radius:20px}@media(max-width:650px){.wadfun-gallery-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.wadfun-gallery-card{padding:7px;border-radius:18px}.wadfun-gallery-actions button{font-size:12px;padding:8px 3px}}';document.head.appendChild(s)}
async function list(){await load();return (await window.wadfunStorage.getAllArtworks()).filter(w=>!w.draft)}
async function render(){const g=document.getElementById('galleryGrid');if(!g)return;styles();const a=await list();g.classList.add('wadfun-gallery-grid');if(!a.length){g.innerHTML='<div class="wadfun-gallery-empty">🎨✨<br>ยังไม่มีผลงานเลย</div>';return}g.innerHTML=a.map(w=>{const id=esc(w.id),src=esc(image(w));return '<article class="wadfun-gallery-card"><button class="wadfun-gallery-thumb" onclick="wadfunOpenWork(\''+id+'\')"><img src="'+src+'" alt="ผลงานของฉัน"></button><div class="wadfun-gallery-actions"><button class="primary" onclick="wadfunOpenWork(\''+id+'\')">👀 ดู</button><button class="wadfun-gallery-share" onclick="wadfunShareWork(\''+id+'\')">📤 แชร์</button></div><button class="danger" style="width:100%;margin-top:6px" onclick="wadfunDeleteWork(\''+id+'\')">🗑️ ลบ</button></article>'}).join('')}
let viewerId=null;
function ensureViewer(){if(document.getElementById('wadfunViewer'))return;const s=document.createElement('style');s.textContent='.wadfun-viewer{display:none;position:fixed;inset:0;z-index:99999;background:rgba(20,43,57,.94);align-items:center;justify-content:center;padding:8px}.wadfun-viewer.open{display:flex}.wadfun-viewer-card{background:#fff;border-radius:24px;padding:10px;width:min(900px,96vw);height:min(94dvh,900px);display:flex;flex-direction:column}.wadfun-viewer-stage{flex:1;min-height:0;display:flex;align-items:center;justify-content:center;overflow:hidden}.wadfun-viewer-stage img{max-width:100%;max-height:100%;object-fit:contain}.wadfun-viewer-actions{display:flex;gap:8px;padding-top:8px}.wadfun-viewer-actions button{flex:1;padding:11px;border-radius:14px;font-weight:1000}';document.head.appendChild(s);const v=document.createElement('div');v.id='wadfunViewer';v.className='wadfun-viewer';v.innerHTML='<div class="wadfun-viewer-card"><button onclick="wadfunCloseViewer()">✕ ปิด</button><div class="wadfun-viewer-stage"><img id="wadfunViewerImg"></div><div class="wadfun-viewer-actions"><button onclick="wadfunShareViewer()">📤 แชร์</button></div></div>';v.addEventListener('click',e=>{if(e.target===v)closeViewer()});document.body.appendChild(v)}
function closeViewer(){document.getElementById('wadfunViewer')?.classList.remove('open');viewerId=null}
async function openWork(id){await load();const w=await window.wadfunStorage.getArtwork(id);if(!image(w))return;ensureViewer();viewerId=String(id);document.getElementById('wadfunViewerImg').src=image(w);document.getElementById('wadfunViewer').classList.add('open')}
async function shareWork(id){await load();const w=await window.wadfunStorage.getArtwork(id),src=image(w);if(!src)return;if(navigator.share){try{const b=await fetch(src).then(r=>r.blob()),f=new File([b],'Wadfun.png',{type:b.type||'image/png'});if(navigator.canShare?.({files:[f]}))return navigator.share({title:w?.name||'ผลงาน Wadfun',files:[f]});return navigator.share({title:w?.name||'ผลงาน Wadfun'})}catch(e){if(e.name!=='AbortError')console.error(e)}}}
async function deleteWork(id){if(!confirm('ลบผลงานนี้ใช่ไหม?'))return;await load();await window.wadfunStorage.deleteArtwork(id);render()}
function editWork(id){return false}
function hookGallery(){if(hookedGallery)return true;if(typeof window.gallery!=='function')return false;const old=window.gallery;window.gallery=async function(){try{await old.apply(this,arguments)}catch(e){console.error('[Wadfun] legacy gallery failed',e)}try{await render()}catch(e){console.error('[Wadfun] gallery render failed',e)}};hookedGallery=true;return true}
function hookShow(){if(hookedShow||typeof window.show!=='function')return false;const oldShow=window.show;window.show=async function(id){if(!finishing&&active()==='color'&&id!=='color'){const snap=captureColorSnapshot();if(snap)window.wadfunColorAutosaveReady=saveCurrentColor(snap);if(window.wadfunColorAutosaveReady)await window.wadfunColorAutosaveReady;window.wadfunColorAutosaveReady=null}return oldShow.apply(this,arguments)};hookedShow=true;return true}
function installColorAutosave(){if(autoObserver||!document.body)return;if(!document.getElementById('color'))return;let wasColorActive=active()==='color';autoObserver=new MutationObserver(()=>{const now=active()==='color';if(!finishing&&wasColorActive&&!now){const snap=captureColorSnapshot();if(snap)window.wadfunColorAutosaveReady=saveCurrentColor(snap)}wasColorActive=now});autoObserver.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
function boot(){cleanHomeMenu();hookShow();installColorExitCapture();installColorAutosave();let n=0;const t=setInterval(()=>{cleanHomeMenu();hookFinish();hookGallery();hookShow();installColorExitCapture();installColorAutosave();if(++n>300||hookedFinish&&hookedGallery&&hookedColorExit&&autoObserver)clearInterval(t)},100);load().then(render).catch(console.error)}
window.wadfunFinish=finish;window.wadfunOpenWork=openWork;window.wadfunShareWork=shareWork;window.wadfunDeleteWork=deleteWork;window.wadfunEditWork=()=>false;window.wadfunCloseViewer=closeViewer;window.wadfunEditViewer=()=>false;window.wadfunShareViewer=()=>viewerId&&shareWork(viewerId);window.wadfunGallery={render,saveCurrentArtwork:save,saveCurrentColor,editWork};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
