/* Wadfun Gallery Engine V2 — child-friendly local gallery */
(function(){
'use strict';
const KEY='wadfunWorks';
function works(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}
function save(a){localStorage.setItem(KEY,JSON.stringify(a))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function get(id){return works().find(x=>String(x.id)===String(id))}
function downloadWork(id){const w=get(id);if(!w?.img)return;const a=document.createElement('a');a.href=w.img;a.download='Wadfun-'+String(w.name||'ผลงาน').replace(/[^\u0E00-\u0E7Fa-zA-Z0-9_-]+/g,'_')+'.png';document.body.appendChild(a);a.click();a.remove()}
async function shareWork(id){const w=get(id);if(!w?.img)return;try{if(navigator.share){let file=null;try{const r=await fetch(w.img);const b=await r.blob();file=new File([b],'Wadfun.png',{type:b.type||'image/png'})}catch(e){}if(file&&navigator.canShare?.({files:[file]})){await navigator.share({title:'ผลงานจาก Wadfun',text:w.name||'ผลงานของฉัน',files:[file]})}else await navigator.share({title:'ผลงานจาก Wadfun',text:w.name||'ผลงานของฉัน'})}else downloadWork(id)}catch(e){if(e?.name!=='AbortError')downloadWork(id)}}
function renameWork(id){const w=get(id);if(!w)return;const name=prompt('ตั้งชื่อผลงานของฉัน ✏️',w.name||'ผลงานของฉัน');if(name===null)return;w.name=name.trim()||'ผลงานของฉัน';save(works());render();openViewer(id)}
function openWork(id){const w=get(id);if(!w?.img)return;ensureViewer();const title=document.getElementById('wadfunViewerTitle');const img=document.getElementById('wadfunViewerImg');title.textContent=w.name||'ผลงานของฉัน';img.src=w.img;img.alt=w.name||'ผลงาน';document.getElementById('wadfunViewer').dataset.id=String(id);document.getElementById('wadfunViewer').classList.add('open');document.body.classList.add('wadfun-viewer-open')}
function closeViewer(){const v=document.getElementById('wadfunViewer');if(v){v.classList.remove('open');document.body.classList.remove('wadfun-viewer-open')}}
function ensureViewer(){if(document.getElementById('wadfunViewer'))return;const s=document.createElement('style');s.textContent='.wadfun-viewer-open{overflow:hidden}.wadfun-viewer{display:none;position:fixed;inset:0;z-index:99999;background:rgba(20,43,57,.94);padding:12px;align-items:center;justify-content:center}.wadfun-viewer.open{display:flex}.wadfun-viewer-card{width:min(960px,100%);height:min(94dvh,900px);background:#fff;border-radius:28px;padding:14px;display:flex;flex-direction:column;box-shadow:0 20px 60px rgba(0,0,0,.3)}.wadfun-viewer-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:2px 2px 10px}.wadfun-viewer-head b{font-size:22px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.wadfun-viewer-close{width:44px;height:44px;border-radius:50%;background:#ffe6e8;font-size:24px;font-weight:1000}.wadfun-viewer-stage{flex:1;min-height:0;border-radius:20px;background:#f5fbff;display:flex;align-items:center;justify-content:center;overflow:hidden}.wadfun-viewer-stage img{max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain;display:block}.wadfun-viewer-actions{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;padding-top:10px}.wadfun-viewer-actions button{min-width:110px}.wadfun-share{background:#e8f7ff;border:2px solid #bfe6f7;border-radius:16px;padding:11px 15px;font-weight:1000}.wadfun-edit{background:#fff4cf;border:2px solid #e6c56a;border-radius:16px;padding:11px 15px;font-weight:1000}@media(max-width:600px){.wadfun-viewer{padding:6px}.wadfun-viewer-card{height:calc(100dvh - 12px);border-radius:22px;padding:9px}.wadfun-viewer-head b{font-size:18px}.wadfun-viewer-actions button{flex:1;min-width:0}.wadfun-viewer-stage{border-radius:16px}}';document.head.appendChild(s);const v=document.createElement('div');v.id='wadfunViewer';v.className='wadfun-viewer';v.innerHTML='<div class="wadfun-viewer-card" role="dialog" aria-modal="true"><div class="wadfun-viewer-head"><b id="wadfunViewerTitle">ผลงานของฉัน</b><button class="wadfun-viewer-close" type="button" aria-label="ปิด" onclick="closeWorkViewer()">×</button></div><div class="wadfun-viewer-stage"><img id="wadfunViewerImg" alt="ผลงาน"></div><div class="wadfun-viewer-actions"><button class="primary" type="button" onclick="renameWorkViewer()">✏️ ตั้งชื่อ</button><button class="wadfun-share" type="button" onclick="shareWorkViewer()">📤 แชร์</button><button class="roundBtn" type="button" onclick="downloadWorkViewer()">💾 บันทึก</button></div></div>';v.addEventListener('click',e=>{if(e.target===v)closeViewer()});document.body.appendChild(v)}
function currentId(){return document.getElementById('wadfunViewer')?.dataset.id}
function openViewer(id){openWork(id)}
function closeWorkViewer(){closeViewer()}
function renameWorkViewer(){const id=currentId();if(id)renameWork(id)}
function shareWorkViewer(){const id=currentId();if(id)shareWork(id)}
function downloadWorkViewer(){const id=currentId();if(id)downloadWork(id)}
function render(){const g=document.getElementById('galleryGrid');if(!g)return;const a=works();g.innerHTML=a.length?a.map(w=>`<div class="work"><button type="button" style="display:block;width:100%;padding:0;background:none;border-radius:14px" aria-label="เปิด ${esc(w.name||'ผลงาน')}" onclick="openWork(${w.id})"><img src="${w.img}" alt="${esc(w.name||'ผลงาน')}" loading="lazy" style="cursor:pointer"></button><b>${esc(w.name||'ผลงานของฉัน')}</b><small>${esc(w.date||'')}</small><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px"><button class="primary" style="padding:9px 6px" onclick="openWork(${w.id})">ดูรูป</button><button class="roundBtn" style="padding:9px 6px" onclick="downloadWork(${w.id})">💾 บันทึก</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px"><button class="roundBtn" style="padding:9px 6px" onclick="renameWork(${w.id})">✏️ ตั้งชื่อ</button><button class="wadfun-share" style="padding:9px 6px" onclick="shareWork(${w.id})">📤 แชร์</button></div><button class="danger" style="width:100%;margin-top:6px" onclick="deleteWork(${w.id})">ลบ</button></div>`).join(''):'<div class="help" style="grid-column:1/-1;text-align:center">ยังไม่มีผลงานเลย ✨<br>ลองวาดหรือระบายสีสักรูปนะ</div>'}
window.downloadWork=downloadWork;window.openWork=openWork;window.renameWork=renameWork;window.shareWork=shareWork;window.closeWorkViewer=closeWorkViewer;window.renameWorkViewer=renameWorkViewer;window.shareWorkViewer=shareWorkViewer;window.downloadWorkViewer=downloadWorkViewer;
const oldGallery=window.gallery;window.gallery=function(){if(typeof oldGallery==='function')oldGallery();render()};
const oldDelete=window.deleteWork;window.deleteWork=function(id){if(!get(id))return;if(!confirm('ลบผลงานนี้ใช่ไหม?'))return;save(works().filter(w=>String(w.id)!==String(id)));render();if(typeof parent==='function')parent()};
function boot(){render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
