/* Wadfun Gallery Engine V4 — child-friendly local gallery + continue editing */
(function(){
'use strict';
const KEY='wadfunWorks';
function works(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}
function save(a){localStorage.setItem(KEY,JSON.stringify(a))}
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function get(id){return works().find(x=>String(x.id)===String(id))}
function downloadWork(id){const w=get(id);if(!w?.img)return;const a=document.createElement('a');a.href=w.img;a.download='Wadfun-'+String(w.name||'ผลงาน').replace(/[^\u0E00-\u0E7Fa-zA-Z0-9_-]+/g,'_')+'.png';document.body.appendChild(a);a.click();a.remove()}
async function shareWork(id){const w=get(id);if(!w?.img)return;try{if(navigator.share){let file=null;try{const r=await fetch(w.img);const b=await r.blob();file=new File([b],'Wadfun.png',{type:b.type||'image/png'})}catch(e){}if(file&&navigator.canShare?.({files:[file]})){await navigator.share({title:'ผลงานจาก Wadfun',text:w.name||'ผลงานของฉัน',files:[file]})}else await navigator.share({title:'ผลงานจาก Wadfun',text:w.name||'ผลงานของฉัน'})}else downloadWork(id)}catch(e){if(e?.name!=='AbortError')downloadWork(id)}}
function renameWork(id){const w=get(id);if(!w)return;const name=prompt('ตั้งชื่อผลงานของฉัน ✏️',w.name||'ผลงานของฉัน');if(name===null)return;w.name=name.trim()||'ผลงานของฉัน';save(works());render();openWork(id)}
function loadImageIntoActiveCanvas(w){return new Promise(resolve=>{const canvas=document.querySelector('.screen.active canvas.canvas')||document.querySelector('.screen.active canvas');if(!canvas){resolve(false);return}const img=new Image();img.onload=()=>{try{const r=canvas.getBoundingClientRect();const W=Math.max(1,Math.round(r.width||canvas.width||img.naturalWidth));const H=Math.max(1,Math.round(r.height||canvas.height||img.naturalHeight));canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);const scale=Math.min(W/img.naturalWidth,H/img.naturalHeight);const dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;ctx.drawImage(img,(W-dw)/2,(H-dh)/2,dw,dh);canvas.dispatchEvent(new Event('wadfun-work-loaded'));resolve(true)}catch(e){resolve(false)}};img.onerror=()=>resolve(false);img.src=w.img})}
function editWork(id){const w=get(id);if(!w?.img)return;const mode=w.mode==='color'?'color':'draw';closeViewer();let opened=false;try{if(typeof window.show==='function'){window.show(mode);opened=true}}catch(e){}if(!opened){const candidates=[...document.querySelectorAll('button')];const wanted=mode==='color'?['ระบายสี','เริ่มระบายสี']:['วาดเอง','เริ่มวาด'];const b=candidates.find(x=>wanted.some(t=>(x.textContent||'').includes(t)));if(b){b.click();opened=true}}setTimeout(()=>{loadImageIntoActiveCanvas(w);if(mode==='color'){try{window.wadfunColorTemplateChanged?.()}catch(e){}}},opened?180:0)}
function openWork(id){const w=get(id);if(!w?.img)return;ensureViewer();document.getElementById('wadfunViewerTitle').textContent=w.name||'ผลงานของฉัน';const img=document.getElementById('wadfunViewerImg');img.src=w.img;img.alt=w.name||'ผลงาน';document.getElementById('wadfunViewer').dataset.id=String(id);document.getElementById('wadfunViewer').classList.add('open');document.body.classList.add('wadfun-viewer-open')}
function closeViewer(){const v=document.getElementById('wadfunViewer');if(v){v.classList.remove('open');document.body.classList.remove('wadfun-viewer-open')}}
function ensureViewer(){if(document.getElementById('wadfunViewer'))return;const s=document.createElement('style');s.textContent='.wadfun-viewer-open{overflow:hidden}.wadfun-viewer{display:none;position:fixed;inset:0;z-index:99999;background:rgba(20,43,57,.94);padding:12px;align-items:center;justify-content:center}.wadfun-viewer.open{display:flex}.wadfun-viewer-card{width:min(960px,100%);height:min(94dvh,900px);background:#fff;border-radius:28px;padding:14px;display:flex;flex-direction:column;box-shadow:0 20px 60px rgba(0,0,0,.3)}.wadfun-viewer-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:2px 2px 10px}.wadfun-viewer-head b{font-size:22px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.wadfun-viewer-close{width:44px;height:44px;border-radius:50%;background:#ffe6e8;font-size:24px;font-weight:1000}.wadfun-viewer-stage{flex:1;min-height:0;border-radius:20px;background:#f5fbff;display:flex;align-items:center;justify-content:center;overflow:hidden}.wadfun-viewer-stage img{max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain;display:block}.wadfun-viewer-actions{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;padding-top:10px}.wadfun-viewer-actions button{min-width:110px}.wadfun-share{background:#e8f7ff;border:2px solid #bfe6f7;border-radius:16px;padding:11px 15px;font-weight:1000}.wadfun-edit{background:#fff4cf;border:2px solid #e6c56a;border-radius:16px;padding:11px 15px;font-weight:1000}@media(max-width:600px){.wadfun-viewer{padding:6px}.wadfun-viewer-card{height:calc(100dvh - 12px);border-radius:22px;padding:9px}.wadfun-viewer-head b{font-size:18px}.wadfun-viewer-actions button{flex:1;min-width:0}.wadfun-viewer-stage{border-radius:16px}}';document.head.appendChild(s);const v=document.createElement('div');v.id='wadfunViewer';v.className='wadfun-viewer';v.innerHTML='<div class="wadfun-viewer-card" role="dialog" aria-modal="true"><div class="wadfun-viewer-head"><b id="wadfunViewerTitle">ผลงานของฉัน</b><button class="wadfun-viewer-close" type="button" aria-label="ปิด" onclick="closeWorkViewer()">×</button></div><div class="wadfun-viewer-stage"><img id="wadfunViewerImg" alt="ผลงาน"></div><div class="wadfun-viewer-actions"><button class="primary" type="button" onclick="editWorkViewer()">✏️ แก้ไขต่อ</button><button class="primary" type="button" onclick="renameWorkViewer()">✏️ ตั้งชื่อ</button><button class="wadfun-share" type="button" onclick="shareWorkViewer()">📤 แชร์</button><button class="roundBtn" type="button" onclick="downloadWorkViewer()">💾 บันทึก</button></div></div>';v.addEventListener('click',e=>{if(e.target===v)closeViewer()});document.body.appendChild(v)}
function currentId(){return document.getElementById('wadfunViewer')?.dataset.id}
function closeWorkViewer(){closeViewer()}
function editWorkViewer(){const id=currentId();if(id)editWork(id)}
function renameWorkViewer(){const id=currentId();if(id)renameWork(id)}
function shareWorkViewer(){const id=currentId();if(id)shareWork(id)}
function downloadWorkViewer(){const id=currentId();if(id)downloadWork(id)}
function injectGalleryStyle(){if(document.getElementById('wadfun-gallery-v4'))return;const s=document.createElement('style');s.id='wadfun-gallery-v4';s.textContent='.wadfun-gallery-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px;padding:14px 16px;border-radius:22px;background:linear-gradient(135deg,#e5f8ff,#fff1f8);border:2px solid #dceef6}.wadfun-gallery-head h1{margin:0;font-size:28px}.wadfun-gallery-count{background:#fff;border:2px solid #d9edf7;border-radius:99px;padding:8px 13px;font-weight:1000;white-space:nowrap}.wadfun-gallery-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.wadfun-gallery-card{background:#fff;border:2px solid #e2edf2;border-radius:24px;padding:9px;box-shadow:0 8px 22px rgba(43,93,112,.09);overflow:hidden}.wadfun-gallery-thumb{display:block;width:100%;aspect-ratio:1;padding:0;border-radius:18px;background:#f7fbfd;overflow:hidden}.wadfun-gallery-thumb img{width:100%;height:100%;object-fit:contain;display:block}.wadfun-gallery-name{display:block;margin:9px 5px 2px;font-size:17px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.wadfun-gallery-date{display:block;margin:0 5px;color:#78909c;font-size:12px}.wadfun-gallery-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.wadfun-gallery-actions button{padding:9px 5px}.wadfun-gallery-edit{grid-column:1/-1;background:#fff4cf;border:2px solid #e6c56a;border-radius:16px;padding:10px 6px;font-weight:1000}.wadfun-gallery-empty{text-align:center;padding:42px 18px;background:#fffdf0;border:2px dashed #efd47a;border-radius:24px;font-weight:900;font-size:18px}@media(max-width:950px){.wadfun-gallery-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:650px){.wadfun-gallery-head{padding:11px 12px}.wadfun-gallery-head h1{font-size:22px}.wadfun-gallery-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.wadfun-gallery-card{border-radius:18px;padding:7px}.wadfun-gallery-thumb{border-radius:14px}.wadfun-gallery-name{font-size:14px;margin-top:7px}.wadfun-gallery-actions button{font-size:12px;padding:8px 4px}.wadfun-gallery-empty{grid-column:1/-1}}';document.head.appendChild(s)}
function render(){const g=document.getElementById('galleryGrid');if(!g)return;injectGalleryStyle();const a=works();g.classList.add('wadfun-gallery-grid');g.innerHTML=a.length?'<div class="wadfun-gallery-head" style="grid-column:1/-1"><h1>🖼️ ผลงานของฉัน</h1><span class="wadfun-gallery-count">'+a.length+' รูป ✨</span></div>'+a.map(w=>`<article class="wadfun-gallery-card"><button type="button" class="wadfun-gallery-thumb" aria-label="เปิด ${esc(w.name||'ผลงาน')}" onclick="openWork(${w.id})"><img src="${w.img}" alt="${esc(w.name||'ผลงาน')}" loading="lazy"></button><b class="wadfun-gallery-name">${esc(w.name||'ผลงานของฉัน')}</b><small class="wadfun-gallery-date">${esc(w.date||'')}</small><div class="wadfun-gallery-actions"><button class="wadfun-gallery-edit" onclick="editWork(${w.id})">✏️ แก้ไขต่อ</button><button class="primary" onclick="openWork(${w.id})">👀 ดู</button><button class="roundBtn" onclick="renameWork(${w.id})">✏️ ชื่อ</button><button class="roundBtn" onclick="downloadWork(${w.id})">💾 บันทึก</button><button class="wadfun-share" onclick="shareWork(${w.id})">📤 แชร์</button></div><button class="danger" style="width:100%;margin-top:6px" onclick="deleteWork(${w.id})">🗑️ ลบ</button></article>`).join(''):'<div class="wadfun-gallery-empty"><div style="font-size:52px">🎨✨</div>ยังไม่มีผลงานเลย<br><small>ลองวาดหรือระบายสีสักรูปนะ!</small></div>'}
function tagSavedWork(){try{const a=works();const active=document.querySelector('.screen.active');const mode=active?.id==='color'?'color':active?.id==='draw'?'draw':null;if(!mode)return;const id=Date.now();const last=a.slice().reverse().find(w=>String(w.id)===String(id));if(last)last.mode=mode;else if(a.length){a[a.length-1].mode=mode}save(a)}catch(e){}}
const oldSaveCanvas=window.saveCanvas;window.saveCanvas=function(){const r=typeof oldSaveCanvas==='function'?oldSaveCanvas.apply(this,arguments):undefined;setTimeout(tagSavedWork,0);return r};
const oldGallery=window.gallery;window.gallery=function(){if(typeof oldGallery==='function')oldGallery();render()};
const oldDelete=window.deleteWork;window.deleteWork=function(id){if(!get(id))return;if(!confirm('ลบผลงานนี้ใช่ไหม?'))return;save(works().filter(w=>String(w.id)!==String(id)));render();if(typeof parent==='function')parent()};
window.editWork=editWork;window.editWorkViewer=editWorkViewer;window.downloadWork=downloadWork;window.openWork=openWork;window.renameWork=renameWork;window.shareWork=shareWork;window.closeWorkViewer=closeWorkViewer;window.renameWorkViewer=renameWorkViewer;window.shareWorkViewer=shareWorkViewer;window.downloadWorkViewer=downloadWorkViewer;
function boot(){render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
