/* Wadfun Responsive Workspace V8 — fixed toolbar + reliable pinch zoom */
(function(){
'use strict';
const $=id=>document.getElementById(id);
function workspaceOn(){return $('draw')?.classList.contains('active')||$('color')?.classList.contains('active')}
function readColor(){
 const els=[$('drawDot'),$('colorDot')].filter(Boolean);
 for(const el of els){const bg=getComputedStyle(el).backgroundColor,m=(bg||'').match(/\d+(?:\.\d+)?/g);if(m&&m.length>=3)return '#'+m.slice(0,3).map(v=>Math.round(+v).toString(16).padStart(2,'0')).join('').toUpperCase()}
 return window.wadfunSelectedColor||'#E53935';
}
function syncSelectedColor(){
 const c=readColor();window.wadfunSelectedColor=c;
 [$('drawDot'),$('colorDot')].forEach(el=>{if(el){el.style.setProperty('background-color',c,'important');el.style.setProperty('background',c,'important');el.dataset.selectedColor=c;el.title='สีที่เลือก '+c}});
 document.querySelectorAll('.colorMini').forEach(el=>{el.style.setProperty('background-color',c,'important');el.style.setProperty('background',c,'important')});
 const btn=$('drawDot')?.closest('button');if(btn){btn.dataset.selectedColor=c;btn.setAttribute('aria-label','สีที่เลือก '+c)}
}
function cleanHint(){document.querySelectorAll('.floatHint').forEach(el=>el.style.display='none')}
function zoomLayer(type){return $(type==='draw'?'drawZoom':'colorZoom')}
function setZoom(type,scale){scale=Math.max(1,Math.min(3,Number(scale)||1));const layer=zoomLayer(type);if(layer)layer.style.transform=`scale(${scale})`;const hud=document.querySelector(`.wadfunZoomHud[data-zoom-type="${type}"]`),pct=hud?.querySelector('.wadfunZoomPct');if(pct)pct.textContent=Math.round(scale*100)+'%'}
function resetZoom(type){const st=window.wadfunPinchStates?.[type];if(st){st.scale=1;st.startScale=1;st.startDist=0;st.touches.clear()}setZoom(type,1)}
function ensureZoomHud(type){if(!workspaceOn())return;let hud=document.querySelector(`.wadfunZoomHud[data-zoom-type="${type}"]`);if(!hud){hud=document.createElement('div');hud.className='wadfunZoomHud';hud.dataset.zoomType=type;hud.innerHTML='<span class="wadfunZoomPct">100%</span><button type="button" class="wadfunZoomReset">100%</button>';document.body.appendChild(hud);hud.querySelector('.wadfunZoomReset').addEventListener('click',()=>resetZoom(type))}}
function lockToolbar(section){const page=section.querySelector('.drawPage'),area=section.querySelector('.canvasArea'),toolbar=section.querySelector('.toolbar');if(!page||!toolbar)return;page.style.width='100%';page.style.height='calc(100dvh - env(safe-area-inset-top) - env(safe-area-inset-bottom))';page.style.minHeight='0';page.style.padding='4px';page.style.paddingTop=(toolbar.getBoundingClientRect().height+8)+'px';page.style.borderRadius='0';page.style.overflow='hidden';page.style.display='flex';page.style.flexDirection='column';toolbar.style.position='fixed';toolbar.style.left='0';toolbar.style.right='0';toolbar.style.top='env(safe-area-inset-top)';toolbar.style.zIndex='2000';toolbar.style.flex='none';toolbar.style.width='100vw';toolbar.style.maxWidth='100vw';toolbar.style.overflowX='auto';toolbar.style.overflowY='hidden';toolbar.style.background='linear-gradient(#fff,#edf9ff)';toolbar.style.boxSizing='border-box';if(area){area.style.width='100%';area.style.flex='1 1 auto';area.style.height='auto';area.style.minHeight='0';area.style.marginTop='4px';area.style.borderRadius='12px';area.style.overflow='hidden'}const view=section.querySelector('.canvasViewport'),layer=section.querySelector('.zoomLayer');if(view){view.style.width='100%';view.style.height='100%';view.style.touchAction='none'}if(layer){layer.style.width='100%';layer.style.height='100%';layer.style.display='flex';layer.style.alignItems='center';layer.style.justifyContent='center';layer.style.transformOrigin='center center';layer.style.willChange='transform'}ensureZoomHud(section.id==='draw'?'draw':'color')}
function sync(){const on=workspaceOn();document.documentElement.classList.toggle('wadfun-workspace',on);document.body.classList.toggle('wadfun-workspace',on);const top=document.querySelector('.top');if(top)top.style.display=on?'none':'';const app=document.querySelector('.app');if(app){app.style.maxWidth=on?'none':'';app.style.width=on?'100vw':'';app.style.padding=on?'0':'';app.style.margin=on?'0':''}['draw','color'].forEach(id=>{const s=$(id);if(!s||!s.classList.contains('active'))return;lockToolbar(s)});cleanHint();syncSelectedColor()}
function fitInitialCanvas(id,viewportId){const c=$(id),v=$(viewportId);if(!c||!v||c.dataset.fitted==='1')return;const r=v.getBoundingClientRect();if(r.width<50||r.height<50)return;const old=c.width&&c.height?c.toDataURL('image/png'):null,d=Math.min(devicePixelRatio||1,2);c.style.width=r.width+'px';c.style.height=r.height+'px';c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.dataset.fitted='1';if(old){const img=new Image();img.onload=()=>{const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height)};img.src=old}}
function fitAfterShow(){sync();requestAnimationFrame(()=>{sync();fitInitialCanvas('drawCanvas','drawViewport');fitInitialCanvas('colorCanvas','colorViewport')})}
function hookColorPicker(){if(typeof window.pickColor==='function'&&!window.pickColor.__wadfunV8){const old=window.pickColor;const wrapped=function(c){const r=old.apply(this,arguments);setTimeout(syncSelectedColor,0);return r};wrapped.__wadfunV8=true;window.pickColor=wrapped}if(typeof window.setHue==='function'&&!window.setHue.__wadfunV8){const old=window.setHue;const wrapped=function(){const r=old.apply(this,arguments);setTimeout(syncSelectedColor,0);return r};wrapped.__wadfunV8=true;window.setHue=wrapped}if(typeof window.setShade==='function'&&!window.setShade.__wadfunV8){const old=window.setShade;const wrapped=function(){const r=old.apply(this,arguments);setTimeout(syncSelectedColor,0);return r};wrapped.__wadfunV8=true;window.setShade=wrapped}}
const style=document.createElement('style');style.textContent=`.wadfunZoomHud{position:fixed;right:12px;bottom:12px;z-index:2100;display:flex;align-items:center;gap:6px;padding:5px 6px 5px 10px;background:#fff;border:2px solid #d6eaf3;border-radius:16px;box-shadow:0 7px 20px #24566a22;font-weight:1000;user-select:none;-webkit-user-select:none}.wadfunZoomPct{min-width:48px;text-align:center;font-size:13px}.wadfunZoomReset{min-width:48px;height:34px;border-radius:11px;background:#eaf8ff;border:2px solid #bfe2f3;font-weight:1000;font-size:12px}`;document.head.appendChild(style);window.wadfunZoomUI={set:setZoom,reset:resetZoom,update:setZoom};window.addEventListener('resize',()=>{clearTimeout(window.__wadResize);window.__wadResize=setTimeout(sync,80)},{passive:true});window.addEventListener('orientationchange',()=>setTimeout(sync,180),{passive:true});window.addEventListener('pageshow',fitAfterShow,{passive:true});const obs=new MutationObserver(()=>{sync();requestAnimationFrame(()=>{fitInitialCanvas('drawCanvas','drawViewport');fitInitialCanvas('colorCanvas','colorViewport')})});obs.observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class']});setInterval(()=>{hookColorPicker();syncSelectedColor();cleanHint()},150);setTimeout(fitAfterShow,0);setTimeout(fitAfterShow,250);window.wadfunResponsiveV8={sync,fitAfterShow,syncSelectedColor,resetZoom,setZoom};})();