/* Wadfun Zoom Slider V5 — 100% minimum, explicit pan mode, no pinch. */
(function(){
'use strict';
const $=id=>document.getElementById(id), state={draw:{s:1,x:0,y:0,pan:false},color:{s:1,x:0,y:0,pan:false}};
function layer(t){return $(t+'Zoom')}
function area(t){return $(t+'Viewport')?.parentElement}
function viewport(t){return $(t+'Viewport')}
function ui(t){return document.querySelector(`[data-wadfun-zoom="${t}"]`)}
function clampPan(t,x,y){const a=area(t),q=state[t];if(!a||q.s<=1)return{x:0,y:0};const r=a.getBoundingClientRect();return{x:Math.max(-r.width*(q.s-1)/2,Math.min(r.width*(q.s-1)/2,x)),y:Math.max(-r.height*(q.s-1)/2,Math.min(r.height*(q.s-1)/2,y))}}
function apply(t){const z=layer(t),u=ui(t);if(!z)return;const q=state[t],p=clampPan(t,q.x,q.y);q.x=p.x;q.y=p.y;z.style.transformOrigin='center center';z.style.transform=`translate3d(${q.x}px,${q.y}px,0) scale(${q.s})`;if(u){u.querySelector('input').value=q.s;u.querySelector('.wadfunZoomPct').textContent=Math.round(q.s*100)+'%';u.querySelector('[data-z="minus"]').disabled=q.s<=1.0001;u.querySelector('.wadfunPan').classList.toggle('on',q.pan&&q.s>1)}}
function setZoom(t,s){const q=state[t];q.s=Math.max(1,Math.min(3,Number(s)||1));if(q.s<=1){q.s=1;q.x=0;q.y=0;q.pan=false}apply(t)}
function make(t){const a=area(t);if(!a||a.querySelector('[data-wadfun-zoom]'))return;const b=document.createElement('div');b.dataset.wadfunZoom=t;b.className='wadfunZoomUI';b.innerHTML='<button type="button" class="wadfunZoomBtn" data-z="plus" aria-label="ซูมเข้า">＋</button><div class="wadfunZoomPct">100%</div><input type="range" min="1" max="3" step="0.05" value="1" aria-label="ระดับซูม"><button type="button" class="wadfunZoomBtn" data-z="minus" disabled aria-label="ซูมออก">−</button><button type="button" class="wadfunPan" aria-label="เลื่อนภาพ">✋</button><button type="button" class="wadfunZoomReset">100%</button>';b.addEventListener('pointerdown',e=>{e.stopPropagation()}, {capture:true});b.addEventListener('touchstart',e=>e.stopPropagation(),{capture:true,passive:true});b.querySelector('input').addEventListener('input',e=>{e.stopPropagation();setZoom(t,e.target.value)});b.querySelector('[data-z="plus"]').addEventListener('click',e=>{e.stopPropagation();setZoom(t,state[t].s+.1)});b.querySelector('[data-z="minus"]').addEventListener('click',e=>{e.stopPropagation();if(state[t].s>1)setZoom(t,state[t].s-.1)});b.querySelector('.wadfunZoomReset').addEventListener('click',e=>{e.stopPropagation();setZoom(t,1)});b.querySelector('.wadfunPan').addEventListener('click',e=>{e.stopPropagation();if(state[t].s<=1)return;state[t].pan=!state[t].pan;apply(t)});a.appendChild(b);apply(t)}
function bindPan(t){const v=viewport(t);if(!v||v.dataset.wadfunPanV3)return;v.dataset.wadfunPanV3='1';let id=null,lx=0,ly=0;
 const down=e=>{const q=state[t];if(!q.pan||q.s<=1)return;if(e.pointerType==='mouse'&&e.button!==0)return;id=e.pointerId;lx=e.clientX;ly=e.clientY;try{v.setPointerCapture(e.pointerId)}catch(_){ }e.preventDefault();e.stopImmediatePropagation()};
 const move=e=>{if(id!==e.pointerId)return;const q=state[t];q.x+=e.clientX-lx;q.y+=e.clientY-ly;lx=e.clientX;ly=e.clientY;apply(t);e.preventDefault();e.stopImmediatePropagation()};
 const end=e=>{if(id!==e.pointerId)return;try{v.releasePointerCapture(e.pointerId)}catch(_){ }id=null;e.preventDefault();e.stopImmediatePropagation()};
 v.addEventListener('pointerdown',down,{capture:true,passive:false});v.addEventListener('pointermove',move,{capture:true,passive:false});v.addEventListener('pointerup',end,{capture:true,passive:false});v.addEventListener('pointercancel',end,{capture:true,passive:false});
}
function install(){['draw','color'].forEach(t=>{make(t);bindPan(t)});const st=document.createElement('style');st.textContent=`.wadfunZoomHud,.wadfunZoomHUD,.zoomHud,.zoomHUD,.zoom-hud,.zoomHUDWrap,[class*="zoom"][class*="hud"],[id*="zoom"][id*="hud"],[class*="zoom"][class*="percent"],[id*="zoom"][id*="percent"]{display:none!important}.wadfunZoomUI{position:absolute;left:7px;top:50%;transform:translateY(-50%);z-index:40;width:50px;padding:7px 5px;border:2px solid #d5e8f2;border-radius:18px;background:rgba(255,255,255,.95);box-shadow:0 8px 22px rgba(35,90,115,.18);display:flex;flex-direction:column;align-items:center;gap:6px;touch-action:none;user-select:none}.wadfunZoomUI .wadfunZoomBtn{width:38px;height:38px;border-radius:12px;background:#eaf8ff;border:2px solid #cbe8f5;font-size:23px;font-weight:1000;line-height:1;touch-action:none}.wadfunZoomUI .wadfunZoomBtn:disabled{opacity:.38;cursor:not-allowed}.wadfunZoomUI .wadfunZoomPct{font-size:10px;font-weight:1000;min-height:15px}.wadfunZoomUI input{width:190px;height:28px;transform:rotate(-90deg);margin:78px 0;accent-color:#31a9df;touch-action:none}.wadfunZoomUI .wadfunPan{width:38px;height:38px;border-radius:12px;background:#fff6c9;border:2px solid #ecd88a;font-size:19px;touch-action:none}.wadfunZoomUI .wadfunPan.on{outline:3px solid #78cdf1;background:#e9f8ff}.wadfunZoomUI .wadfunZoomReset{font-size:9px;font-weight:1000;border-radius:9px;background:#fff6c9;padding:5px 4px;white-space:nowrap;touch-action:none}.floatHint{display:none!important}@media(max-width:650px){.wadfunZoomUI{left:5px;width:47px;padding:6px 4px}.wadfunZoomUI .wadfunZoomBtn,.wadfunZoomUI .wadfunPan{width:36px;height:36px}.wadfunZoomUI input{margin:72px 0}}`;document.head.appendChild(st);window.wadfunZoomUI={update:(t,s)=>setZoom(t,s),reset:t=>setZoom(t,1),get:t=>state[t].s,pan:(t,on)=>{if(state[t].s>1){state[t].pan=!!on;apply(t)}}};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
