/* Wadfun Zoom Slider V4 — zoom in from 100%; zoom out only back to 100%; no pinch. */
(function(){
'use strict';
const $=id=>document.getElementById(id), state={draw:{s:1,x:0,y:0,pan:false},color:{s:1,x:0,y:0,pan:false}};
function layer(t){return $(t+'Zoom')} function area(t){return $(t+'Viewport')?.parentElement} function viewport(t){return $(t+'Viewport')}
function clampPan(t,x,y){const a=area(t),s=state[t].s;if(!a)return{x,y};const r=a.getBoundingClientRect();return{x:Math.max(-r.width*(s-1)/2,Math.min(r.width*(s-1)/2,x)),y:Math.max(-r.height*(s-1)/2,Math.min(r.height*(s-1)/2,y))}}
function apply(t){const z=layer(t);if(!z)return;const q=state[t],p=clampPan(t,q.x,q.y);q.x=p.x;q.y=p.y;z.style.transformOrigin='center center';z.style.transform=`translate3d(${q.x}px,${q.y}px,0) scale(${q.s})`;const u=document.querySelector(`[data-wadfun-zoom="${t}"]`);if(u){u.querySelector('input').value=q.s;u.querySelector('.wadfunZoomPct').textContent=Math.round(q.s*100)+'%';u.querySelector('[data-z="minus"]').disabled=q.s<=1.0001;u.querySelector('.wadfunPan').classList.toggle('on',q.pan)}}
function setZoom(t,s){state[t].s=Math.max(1,Math.min(3,Number(s)||1));if(state[t].s===1){state[t].x=0;state[t].y=0;state[t].pan=false}apply(t)}
function make(t){const a=area(t);if(!a||a.querySelector('[data-wadfun-zoom]'))return;const b=document.createElement('div');b.dataset.wadfunZoom=t;b.className='wadfunZoomUI';b.innerHTML='<button type="button" class="wadfunZoomBtn" data-z="plus">＋</button><div class="wadfunZoomPct">100%</div><input type="range" min="1" max="3" step="0.05" value="1" aria-label="ระดับซูม"><button type="button" class="wadfunZoomBtn" data-z="minus" disabled>−</button><button type="button" class="wadfunPan">✋</button><button type="button" class="wadfunZoomReset">100%</button>';b.addEventListener('pointerdown',e=>e.stopPropagation(),{capture:true});b.querySelector('input').addEventListener('input',e=>{e.stopPropagation();setZoom(t,e.target.value)});b.querySelector('[data-z="plus"]').addEventListener('click',()=>setZoom(t,state[t].s+.1));b.querySelector('[data-z="minus"]').addEventListener('click',e=>{e.stopPropagation();if(state[t].s>1)setZoom(t,state[t].s-.1)});b.querySelector('.wadfunZoomReset').addEventListener('click',()=>setZoom(t,1));b.querySelector('.wadfunPan').addEventListener('click',()=>{if(state[t].s<=1)return;state[t].pan=!state[t].pan;apply(t)});a.appendChild(b);apply(t)}
function bindPan(t){const v=viewport(t);if(!v||v.dataset.wadfunPanV2)return;v.dataset.wadfunPanV2='1';let id=null,lx=0,ly=0;v.addEventListener('pointerdown',e=>{if(!state[t].pan||state[t].s<=1)return;id=e.pointerId;lx=e.clientX;ly=e.clientY;e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});v.addEventListener('pointermove',e=>{if(id!==e.pointerId)return;const q=state[t];q.x+=e.clientX-lx;q.y+=e.clientY-ly;lx=e.clientX;ly=e.clientY;apply(t);e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});['pointerup','pointercancel'].forEach(ev=>v.addEventListener(ev,e=>{if(id===e.pointerId){id=null;e.preventDefault();e.stopImmediatePropagation()}},{capture:true,passive:false}))}
function install(){['draw','color'].forEach(t=>{make(t);bindPan(t)});const st=document.createElement('style');st.textContent=`.wadfunZoomHud,.wadfunZoomHUD,.zoomHud,.zoomHUD,.zoom-hud,.zoomHUDWrap,[class*="zoom"][class*="hud"],[id*="zoom"][id*="hud"],[class*="zoom"][class*="percent"],[id*="zoom"][id*="percent"]{display:none!important}.wadfunZoomUI{position:absolute;left:7px;top:50%;transform:translateY(-50%);z-index:40;width:50px;padding:7px 5px;border:2px solid #d5e8f2;border-radius:18px;background:rgba(255,255,255,.95);box-shadow:0 8px 22px rgba(35,90,115,.18);display:flex;flex-direction:column;align-items:center;gap:6px;touch-action:none;user-select:none}.wadfunZoomUI .wadfunZoomBtn{width:38px;height:38px;border-radius:12px;background:#eaf8ff;border:2px solid #cbe8f5;font-size:23px;font-weight:1000;line-height:1;touch-action:none}.wadfunZoomUI .wadfunZoomBtn:disabled{opacity:.42;cursor:not-allowed}.wadfunZoomUI .wadfunZoomPct{font-size:10px;font-weight:1000;min-height:15px}.wadfunZoomUI input{width:190px;height:28px;transform:rotate(-90deg);margin:78px 0;accent-color:#31a9df;touch-action:none}.wadfunZoomUI .wadfunPan{width:38px;height:38px;border-radius:12px;background:#fff6c9;border:2px solid #ecd88a;font-size:19px}.wadfunZoomUI .wadfunPan.on{outline:3px solid #78cdf1;background:#e9f8ff}.wadfunZoomUI .wadfunZoomReset{font-size:9px;font-weight:1000;border-radius:9px;background:#fff6c9;padding:5px 4px;white-space:nowrap;touch-action:none}.floatHint{display:none!important}@media(max-width:650px){.wadfunZoomUI{left:5px;width:47px;padding:6px 4px}.wadfunZoomUI .wadfunZoomBtn,.wadfunZoomUI .wadfunPan{width:36px;height:36px}.wadfunZoomUI input{margin:72px 0}}`;document.head.appendChild(st);window.wadfunZoomUI={update:(t,s)=>setZoom(t,s),reset:t=>setZoom(t,1),get:t=>state[t].s};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
